env:
  spring:
    profile: ${SPRING_PROFILE}
  cognito:
    pool-id: ${AWS_COGNITO_POOL_ID}
    client:
      id: ${AWS_COGNITO_CLIENT_ID}
      secret: ${AWS_COGNITO_CLIENT_SECRET}
      callback-uri: ${AWS_COGNITO_CLIENT_CALLBACK_URI}

spring:
  profiles:
    active: ${SPRING_PROFILE}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
