version: "3.7"
services:
  app:
    build: ../../app
    environment:
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID
      - AWS_COGNITO_CLIENT_SECRET
      - AWS_COGNITO_CLIENT_CALLBACK_URI
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - session
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  session:
    image: redis:5-alpine
    ports:
      - "6379"
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  backend:
