version: "2"
services:
  app:
    build: ../../app
    ports:
      - "8080:8080"
    depends_on:
      - session
    links:
      - "session:redis"
  session:
    image: redis:5-alpine
    hostname: redis
    ports:
      - "6379:6379"
